### ISSUE TITLE
Change id to UUID

### ISSUE THREAD

**Issue by austek** [levkhomich/akka-tracing#102]
Is it possible to change the trace_id to UUID instead of Long?

**Comment by levkhomich** [comment]
No. trace_id is defined by protocol specification.

**Comment by austek** [comment]
what protocol are we talking about here. I can't see anything on zipkin.io but samples provided looks more like UUID than Long http://zipkin.io/pages/data_model.html.

Other implementations I've used such as Brave and Finagle uses UUID
