### ISSUE TITLE
Http Tracing Headers - Long vs Hex

### ISSUE THREAD

**Issue by JBlundell** [levkhomich/akka-tracing#68]
Using 0.4 version - We've had some issues integrating this when a traced call comes in from another service. This other service is implemented in Java Spring and as such implements the Brave library. The trace beginning with this Java service and therefore passes the header X-B3-TraceId along. This id is in 64-bit hex format. However, when akka-tracing receives this message, it tries to convert this hex into a Long and throws a NumberFormatException (PlayActorTracing: 46). I've noticed you've changed the code around this in recent commits, I'm wondering if you had any plans to release a new version of the library containing these commits?

**Comment by levkhomich** [comment]
Hi @JBlundell,

Thank you for bug report. Can you provide exact header value? I need to check, if issue still exists.

Speaking about release, it will be on next week.

**Comment by JBlundell** [comment]
Hi Lev,

Thanks for getting back to me! Here is the header details of an example request from a Java Spring service using the brave library.

Request Headers
accept	text/plain, application/json, application/*+json, */*
host	www.cylog.org
connection	Keep-Alive
user-agent	Apache-HttpClient/4.5.1 (Java/1.8.0_51)
X-B3-Sampled	true
X-B3-TraceId	e3372b1adac86ef6
X-B3-SpanId	728577333ef2410e
X-B3-ParentSpanId	e3372b1adac86ef6
X-B3-SpanName	/headers/
content-length	0


Hope this helps. Any more information, please let me know.

Thanks again,

Jack

**Comment by JBlundell** [comment]
Hi @levkhomich,

Is there any progress on this issue or the new release?

Thanks,

Jack

**Comment by levkhomich** [comment]
Tracing context propagation was improved in a couple of previous commits. You can check if it works properly in 0.5-SNAPSHOT.
