### ISSUE TITLE
Does this provide integration/compatability for akka http?

### ISSUE THREAD

**Issue by dylanwilder** [levkhomich/akka-tracing#72]
Is spray/play required?

**Comment by levkhomich** [comment]
akka-http support is planned, but not yet available.

**Comment by dylanwilder** [comment]
thanks. feel free to close or leave open for reference

**Comment by levkhomich** [comment]
Initial integration was introduced in levkhomich/akka-tracing@33710685c6ca3b66e72130ac7ac5e1aa83d796c9. It is available in latest snapshot. You can use [tests](https://github.com/levkhomich/akka-tracing/tree/33710685c6ca3b66e72130ac7ac5e1aa83d796c9/akka-http/src/test/scala/com/github/levkhomich/akka/tracing/http) as a reference.
