### ISSUE TITLE
Unable to set service name using trace.sample for child trace

### ISSUE THREAD

**Issue by mohanpriyadarshi** [levkhomich/akka-tracing#74]
I am new to Zipkin need your help. In Akka actor based model  trying to  set service name to child trace in   trace hierarchy   the requirement is I make multiple calls to different modules want to capture the same in hierarchy able to do that to some extent by creating child but unable to set service name as it take the actor handle name automatically. What is the correct way to do hierarchy model when the same actor make multiple  calls  
testing it on sample code "MohanRequest"  show as unknown service in the UI. Altho it display as a child in hierarchy. Any help appreciated. 

package sample

import java.util
import java.util.UUID
import scala.collection.JavaConversions._
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._
import scala.util.Random

import akka.actor.{ActorSystem, Props, ActorRef, Actor}
import akka.pattern.{ask, pipe}
import akka.util.Timeout

import com.github.levkhomich.akka.tracing.{ActorTracing, TracingSupport}
import com.typesafe.config.ConfigFactory

final case class ExternalRequest(headers: util.Map[String, String], payload: String) extends TracingSupport
final case class ExternalRequest1(headers: util.Map[String, String], payload: String) extends TracingSupport
final case class ExternalResponse(responseCode: Int, payload: String)
final case class InternalRequest(payload: String) extends TracingSupport
final case class MohanRequest(payload: String) extends TracingSupport
final case class MohanResponse(code: Int, payload: String)

final case class InternalResponse(responseCode: Int, payload: String)

class RequestHandler extends Actor with ActorTracing {

  val child: ActorRef = context.actorOf(Props[DelegateActor])
  implicit val askTimeout: Timeout = 100.milliseconds

  override def receive: Receive = {
    case msg @ ExternalRequest(headers, payload) =>
      println("RequestHandler received " + msg)

      // sample request
      trace.sample(msg, this.getClass.getSimpleName)

      // add info about request headers to trace
      headers.foreach { case (k, v) => trace.recordKeyValue(msg, k, v)}
      println("payload",payload)
     val msg1=MohanRequest(payload).asChildOf(msg)
      println(msg1)
      trace.sample(msg1,"superv2")
      trace.record(msg1,"super call")
      Thread.sleep(Random.nextInt(200))
      trace.record(msg1,"super completed")
      //trace.finish(msg1)
      trace.record(msg1,"super1 call")
      Thread.sleep(Random.nextInt(200))
      trace.record(msg1,"super1 completed")
      trace.finish(msg1)
      //MohanResponse(800, s"mohan, $payload").asResponseTo(msg1)

      //InternalResponse(200, s"Hello, $payload").asResponseTo(msg)

      // to trace child request correctly, mark it using asChildOf
      val internal=InternalRequest(payload).asChildOf(msg)

      child ?  internal recover {
        case e: Exception =>
          // trace exception
          trace.record(msg, e)
          InternalResponse(500, "")
      } map {
        case InternalResponse(responseCode, resp) =>
          // close trace by marking response
          ExternalResponse(responseCode, resp + '!').asResponseTo(msg)
      } pipeTo sender
  }
}

class DelegateActor extends Actor with ActorTracing {
  override def receive: Receive = {
    case msg @ InternalRequest(payload) =>
      println("DelegateActor received " + msg)
      trace.sample(msg, this.getClass.getSimpleName)
      // another computation (sometimes leading to timeout processed by recover block above)
      Thread.sleep(Random.nextInt(200))
      sender !
        InternalResponse(200, s"Hello, $payload").asResponseTo(msg)
  }
}

// create actor system and send messages every second
object TraceHierarchy extends App {
  implicit val askTimeout: Timeout = 500.milliseconds
  def random = UUID.randomUUID().toString
  val system = ActorSystem.create("TraceHierarchy", ConfigFactory.load("application"))
  ConfigFactory.load()
  val handler = system.actorOf(Props[RequestHandler])
  handler ? ExternalRequest(Map("userAgent" -> random), random)
  //system.scheduler.schedule(3.seconds, 1.second) {
   // ExternalRequest(Map("userAgent" -> random), random)
   // handler ? ExternalRequest(Map("userAgent" -> random), random)
  //println("end")
 // }
  //system.awaitTermination()
}

**Comment by levkhomich** [comment]
Hello!

What library version do you use? Did you try using `trace.start` instead of `trace.sample` in all cases except first one?

**Comment by mohanpriyadarshi** [comment]
I picked from http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.github.levkhomich%22%20akka- tracing( "com.github.levkhomich" % "akka-tracing-core_2.11" % "0.4",) Look like libray is very old how to get the latest for SBT build?

**Comment by levkhomich** [comment]
You can use 0.5-SNAPSHOT until it's published. See instructions [here](https://github.com/levkhomich/akka-tracing/wiki/Project-setup).

**Comment by mohanpriyadarshi** [comment]
Latest library works. Now the issue is I need to disable Zipkin tracing only in development environment. But should be available in staging and production. How can I do that? since library refer to default conf i.e application.conf unable to set environment level setting.

**Comment by mohanpriyadarshi** [comment]
All looks good. Thanks a lot.
