### ISSUE TITLE
SpanMetadata is very similar to other things, but has a different binary encoding

### ISSUE THREAD

**Issue by adriancole** [levkhomich/akka-tracing#75]
Just browsing through and not sure if this is changeable or not. We've (zipkin) recently started working on a normal binary form for trace identifiers. It mostly adopts TraceId from finagle, but has a slight twist that makes it possible to have a trace id that isn't a trace id. If you use this form, particularly in binary propagation, it might lead to more interop with other systems. Here's an example

https://github.com/openzipkin/brave/blob/master/brave-core/src/main/java/com/github/kristofa/brave/SpanId.java#L55

**Comment by levkhomich** [comment]
As you properly noticed, SpanMetadata serves the same role, so its serialization will be updated. Another important thing is that now Zipkin supports more flags, and it should definitely addressed on our side. Created #78 for it.

Thank you for information!

**Comment by adriancole** [comment]
any time!
