### ISSUE TITLE
Don't break on 128bit X-B3-TraceId by tossing high bits

### ISSUE THREAD

**Issue by adriancole** [levkhomich/akka-tracing#84]
#### Problem

The first step of transitioning to 128bit `X-B3-TraceId` is tolerantly reading 32 character long ids. Until a change is made, those propagating 128bit ids to akka will have their traces restarted due to a parse failure.

akka-tracing is one of the last libraries that [need an update](https://github.com/openzipkin/b3-propagation/issues/6).

#### Proposal

Change the `SpanMetadata.idFromString` to leniently parse an unsigned 64bit long from a lower-hex string. This could address 128bit (32 character) ids by throwing away the high bits (any characters left of 16 characters)

#### Test

When a 128bit id like `X-B3-TraceId: 463ac35c9f6413ad48485a3953bb6124` is received, the lower 64 bits (right most 16 characters ex48485a3953bb6124) will become the trace id as opposed to having the trace restarted.

#### See also
https://github.com/twitter/finagle/pull/553
https://github.com/openzipkin/brave/pull/239

**Comment by levkhomich** [comment]
Thank you for pinging me -- was not aware about that change. Parser accepts up to 32 character strings now. Implementation is tested against Brave. I've just published it to Maven Central, so it will appear in index in a few hours.

**Comment by adriancole** [comment]
sweet. thanks, Lev!
