### ISSUE TITLE
Sending traces with ToResponseMarshallable[Future[T]]

### ISSUE THREAD

**Issue by sgluschenko** [levkhomich/akka-tracing#88]
Hi,

I am using `TracingDirectives#tracedHandleWith` with an expression inside that returns a `Future[T]`, something like:

```
tracedHandleWith("foo") {
  //declare barFut
  barFut.map {
    bar => 
      val v = ... // some computation that needs time
       trace.recordKeyValue(...) //using v here
  }
}
```
(I'm using `map` here to force tracing being present in result expression)

It seems that trace is send to server before an expression inside the future is completed.

The problem here is that I want to add some information about response to tracing, but trace is send to server before I actually have the response.

Is there any way to workaround this, or maybe I'm doing it wrong?

**Comment by levkhomich** [comment]
Merged.
