### ISSUE TITLE
Tracing not working play java project (play framework 2.3.8)

### ISSUE THREAD

**Issue by skdangi** [levkhomich/akka-tracing#91]
Changes I made:
libraryDependencies += "com.github.levkhomich" %% "akka-tracing-play" % "0.5.1"

akka.tracing {
  host = "localhost"
  port = 9410 # default
}

I don't see any data in zipkin.

**Comment by tuhingupta** [comment]
Not sure if this worked for you. But I used akka-tracing to integrate akka with Zipkin. You can find my project written in java at https://github.com/tuhingupta/akka-sample-tracing-java
