### ISSUE TITLE
Publish 0.6 to maven

### ISSUE THREAD

**Issue by jtescher** [levkhomich/akka-tracing#92]
Looks like 0.6 changes were merged a few months ago but not released? Would be great to be able to use this with play 2.5.x.

**Comment by levkhomich** [comment]
It was planned to support scala 2.12, but because of slow adoption it turned to be long overdue. Despite all that 0.6 was just released. It depends on Akka 2.4, Akka HTTP 10.0, and Play 2.5 (no 2.12 support there obviously).
